version: "3.7"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  flask-mysql:
    image: mysql:8
    container_name: flask-mysql
    hostname: flask-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=toor123